[font]
# draw_bold_text_with_bright_colors = false
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# [font.italic.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
