#:schema https://github.com/jdx/mise/raw/refs/heads/main/schema/mise-task.json

# Tasks [Mise Tasks](https://mise.jdx.dev/tasks/#tasks)
#
# [templates](https://mise.jdx.dev/tasks/templates.html)
# [usage](https://usage.jdx.dev/spec/)
# [tera](https://keats.github.io/tera/#template)
# [bash](https://quickref.me/bash.html)
# [bash](https://devhints.io/bash)
# [shellcheck](https://github.com/koalaman/shellcheck/wiki/Directive)
# [task-configuration](https://mise.jdx.dev/tasks/task-configuration.html)
# [sed-cheatsheet](https://gist.github.com/ssstonebraker/6140154)

