{
  lib,
  den,
  inputs,
  ...
}: {
  # Enable the den dendritic module framework with angle-bracket import syntax.
  # <desktop/niri> resolves to modules/gui/desktop/niri-desktop.nix via __findFile.
  # The flake-file + import-tree integration allows the modules/ directory
  # structure to drive all imports and host definitions automatically.
  _module.args.__findFile = den.lib.__findFile;

  imports = [
    (inputs.flake-file.flakeModules.dendritic or {})
    (inputs.den.flakeModules.dendritic or {})
  ];

  # imports = [inputs.den.flakeModules];

  # den.hosts.x86_64-linux.igloo.users.tux = {};
  # den.hosts.x86_64-linux.igloo.users.alice = {};
  # den.homes.x86_64-linux.alice = {};
  #
  # den.aspects.igloo = {
  #   # User TODO: Remove for real host
  #   nixos.fileSystems."/".device = "/dev/no-boot";
  #   nixos.fileSystems."/".fsType = "auto";
  #   nixos.boot.loader.grub.enable = false;
  # };
  #
  # den.aspects.tux = {
  #   includes = [den.batteries.define-user];
  #   user.description = "Bird";
  #
  #   packages = {pkgs, ...}: {
  #     inherit (pkgs) cowsay;
  #   };
  #
  #   tests = {tux, ...}: {
  #     test-tux-is-bird = {
  #       expr = tux.description;
  #       expected = "Bird";
  #     };
  #   };
  # };
  #
  # den.schema.flake-parts.includes = [den.aspects.foo];
  #
  # # enable hm for all users
  # den.schema.user.classes = lib.mkDefault ["homeManager"];
  #
  # den.aspects.foo = {
  #   includes = [den.aspects.bar];
  #
  #   treefmt.settings.on-unmatched = "warn";
  #
  #   devshell.commands = [{package = "cowsay";}];
  #
  #   packages = {pkgs, ...}: {
  #     inherit (pkgs) htop;
  #   };
  # };
  #
  # den.aspects.bar = {
  #   treefmt.programs.nixfmt.enable = true;
  #
  #   tests.test-math-works = {
  #     expr = 22 * 2;
  #     expected = 44;
  #   };
  #
  #   packages = {config, ...}: {
  #     write-files = config.files.writer.drv;
  #   };
  #
  #   files = {pkgs, ...}: {
  #     files = [
  #       {
  #         path_ = "README.md";
  #         drv = pkgs.writeText "README.md" ''
  #           # Example Den custom classes for flake-parts modules and perSystem outputs.
  #
  #           This example showcases Den forward classes for third-party flake-parts modules.
  #
  #           This README is generated by `nix run .#write-files`.
  #
  #           See den.nix and flake-parts.nix
  #         '';
  #       }
  #     ];
  #   };
  #
  #   devshell = {
  #     pkgs,
  #     self',
  #     ...
  #   }: {
  #     commands = [
  #       {
  #         package = self'.packages.write-files;
  #       }
  #     ];
  #     packages = [
  #       pkgs.hello
  #     ];
  #   };
  # };
  #
  # # --- Pipeline wiring ---
  #
  # # Enter flake-parts scope from flake-system.
  # den.schema.flake-system.includes = [den.policies.system-to-flake-parts];
  #
  # # Exclude vanilla packages route — handled via flake-parts scope.
  # den.schema.flake-system.excludes = [den.policies.packages-to-flake];
}
