experimental-features = nix-command flakes pipe-operators
extra-experimental-features = nix-command flakes pipe-operators
accept-flake-config = true
auto-optimise-store = true

trusted-users = root artifex @wheel

include /home/artifex/.config/nix/nix-secrets.conf
