-- Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/Start/

-- Omarchy's bootstrap keeps path setup out of this user config.
-- dofile((os.getenv("OMARCHY_PATH") or "/usr/share/omarchy") .. "/default/hypr/bootstrap.lua")

-- Disable all Omarchy default bindings. Add your own in hypr/bindings.lua.
-- omarchy_default_bindings = false
--
-- Or disable only bindings for Omarchy's preinstalled apps/web apps while
-- keeping core window-manager bindings:
-- omarchy_preinstalled_bindings = false

-- Load Omarchy defaults.
-- require("default.hypr.omarchy")

-- Put your personal overrides in these files. They're loaded after Omarchy's
-- defaults so package updates can improve the defaults without rewriting your
-- ~/.config/hypr files.
require("hypr.monitors")
require("hypr.input")
require("hypr.bindings")
require("hypr.looknfeel")
require("hypr.autostart")

-- Add any other personal Hyprland configuration below.
-- o.window("qemu", { workspace = "5" })

require("hypr.omasettings")

-- Generated by OmaSettings (omasettings:managed) — do not edit by hand.
-- Every value here was set from the OmaSettings window; delete a line
-- to hand that setting back to your own config.

hl.config({
	general = {
		border_size = 1,
	},
})

hl.config({
	decoration = {
		dim_around = 0,
		dim_inactive = true,
		dim_modal = false,
		dim_special = 0,
		dim_strength = 0,
		rounding_power = 1.05,
	},
})

hl.config({
	group = {
		groupbar = {
			font_size = 10,
			height = 12,
		},
	},
})

-- Full opacity: Omarchy tags every window and fades it to 0.985, which
-- multiplies with the opacity settings, so 100% renders at 98.5%.
o.window(".*", { opacity = "1.0 1.0" })
