#!/bin/bash

# Find Cards
# pactl list cards
# Find the desired card you want to restore and set it's available output

# Set profile for your specific card
sleep 1
pactl set-card-profile alsa_card.pci-0000_03_00.1 output:hdmi-stereo-extra1

# Find Sinks
# pactl list short sinks
# Copy the full sink name you want to set as default

# Set it back as default
sleep 1
pactl set-default-sink "alsa_output.pci-0000_03_00.1.hdmi-stereo-extra1"
