#!/usr/bin/env bash

DIR="$HOME/.config/"

# if [ "$1" == "-f" ]; then
#   wezterm start --always-new-process --class 'wezterm-float'
# elif [ "$1" == "-F" ]; then
#   wezterm start --class 'wezterm-fullscreen'
# else
#   wezterm start
# fi

if [ "$1" == "-f" ]; then
  ghostty --class="ghostty.float"
elif [ "$1" == "-F" ]; then
  ghostty --class="ghostty.fullscreen"
else
  ghostty
fi
