theme = "artifex"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-s = ":w"
"A-k" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"A-j" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]

[keys.select]
"A-k" = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
"A-j" = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]

[keys.normal.g]
a = "code_action" # Maps `ga` to show possible code actions

[keys.normal.space]
q = { q = ":quit" }# Maps `space + q` to quit
c = ":buffer-close" # Maps `space +c ` to close current buffer

[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"
"A-x" = "normal_mode"
j = { j = "normal_mode", k = "normal_mode"}
C-c = "normal_mode"
C-s = [":write", "normal_mode"]


[editor]
line-number="relative"
mouse = true
auto-completion = true
cursorline = true
#cursorcolumn = true
auto-format = true
auto-save = true
idle-timeout = 300
completion-trigger-len = 2
auto-info = true
shell = ["sh", "-c"]
bufferline = "multiple"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
true-color = true
#bufferline = "always"

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1


# [editor.whitespace.render]
# space = "all"
# tab = "all"
# newline = "all"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)


[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "total-line-numbers", "workspace-diagnostics", ]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
auto-signature-help = true
display-signature-help-docs = true
# display-inlay-hints = true

[editor.soft-wrap]
enable=true


