{ self, inputs, ... }: {

  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  flake.nixosModules.vmachineHardware =
    {
      config,
      lib,
      pkgs,
      modulesPath,
      ...
    }:
    {
      imports = [
        (modulesPath + "/profiles/qemu-guest.nix")
      ];
      boot = {

        initrd.availableKernelModules = [
          "ahci"
          "virtio_pci"
          "xhci_pci"
          "sr_mod"
          "virtio_blk"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [ "kvm-intel" ];
        extraModulePackages = [ ];
      };

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/d2d06239-14ed-43fd-bc43-9e7ac2b38899";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/9368-1CC2";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/8b72aecf-6c48-47bb-a430-f218bf6232ad"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    };

}
