{
  self,
  inputs,
  ...
}:
{

  flake.homeModules.general = { config, lib, ... }: {

    stylix.targets = {
      bat.enable = true;
      vivid.enable = true;
      btop.enable = true;
    };

    programs = {
      bat = {
        enable = true;
      };
      btop = {
        enable = true;
        themes.stylix = lib.mkForce (with config.lib.stylix.colors.withHashtag; ''
          #Generated by Stylix (Mauve Process / Accent)
          theme[main_bg]="${base00}"
          theme[main_fg]="${base05}"
          theme[title]="${base05}"
          theme[hi_fg]="${base0D}"
          theme[selected_bg]="${base03}"
          theme[selected_fg]="${base0D}"
          theme[inactive_fg]="${base04}"
          theme[graph_text]="${base06}"
          theme[meter_bg]="${base03}"
          theme[proc_misc]="${base06}"
          theme[cpu_box]="${base0E}"
          theme[mem_box]="${base0B}"
          theme[net_box]="${base0C}"
          theme[proc_box]="${base0D}"
          theme[div_line]="${base01}"
          theme[temp_start]="${base0B}"
          theme[temp_mid]="${base0A}"
          theme[temp_end]="${base08}"
          theme[cpu_start]="${base0B}"
          theme[cpu_mid]="${base0A}"
          theme[cpu_end]="${base08}"
          theme[free_start]="${base0A}"
          theme[free_mid]="${base0B}"
          theme[free_end]="${base0B}"
          theme[cached_start]="${base0C}"
          theme[cached_mid]="${base0C}"
          theme[cached_end]="${base0A}"
          theme[available_start]="${base08}"
          theme[available_mid]="${base0A}"
          theme[available_end]="${base0B}"
          theme[used_start]="${base0A}"
          theme[used_mid]="${base09}"
          theme[used_end]="${base08}"
          theme[download_start]="${base0B}"
          theme[download_mid]="${base0A}"
          theme[download_end]="${base08}"
          theme[upload_start]="${base0B}"
          theme[upload_mid]="${base0A}"
          theme[upload_end]="${base08}"
          theme[process_start]="${base0D}"
          theme[process_mid]="${base0E}"
          theme[process_end]="${base08}"
        '');
      };
      television = {
        enable = true;
        enableZshIntegration = true;
      };
    };

  };

  flake.nixosModules.general =
    {
      pkgs,
      config,
      ...
    }:
    let
      selfpkgs = self.packages."${pkgs.stdenv.hostPlatform.system}";
    in
    {

      imports = with self.nixosModules; [
        inputs.nix-index-database.nixosModules.nix-index

        yazi
        zsh
        multiplexer
        editor

        # nightly-neovim

        nix-ld
      ];

      users.users.${config.preferences.user.name} = {
        shell = pkgs.zsh;
      };

      home-manager.users.${config.preferences.user.name} = {
        imports = with self.homeModules; [
          general
        ];
      };

      security.sudo-rs.enable = true;

      fonts.packages = with pkgs; [
        nerd-fonts.symbols-only
        nerd-fonts.fira-mono

        noto-fonts
        corefonts
        unifont
        cm_unicode
      ];

      environment.sessionVariables = {
        EDITOR = "neovim";
      };

      programs = {
        nix-index-database.comma.enable = true;
      };

      environment.systemPackages = with pkgs; [
        # Nix
        nix-index
        inputs.nix-alien.packages.${pkgs.stdenv.hostPlatform.system}.nix-alien

        # Common
        aria2
        wget
        cifs-utils
        inotify-tools
        lshw
        nfs-utils
        ntfs3g
        p7zip
        pciutils
        sshfs
        unzip
        unrar
        zip
        doggo

        # Dev tools
        jq
        git
        github-cli

        # CLI Goodies
        nix-prefetch-scripts
        nix-search-tv
        nix-tree
        ncdu
        dust
        fastfetch
        microfetch
        fd
        file
        fzf
        ghgrab
        smartmontools
        imv
        killall
        lsd
        ripgrep
        starship
        tealdeer
        television
        trash-cli
        vivid
        wget
        zoxide
        superfile

        selfpkgs.nh
        selfpkgs.yazi
        selfpkgs.lazygit
      ];

    };
}
