#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/i3"
STYLE="artifex"
RASI="$DIR/themes/$STYLE/rofi/launcher.rasi"

# Run
rofi \
	-modi emoji \
	-show emoji \
	-kb-custom-1 Ctrl+c \
	-kb-cancel Alt-F1 \
	-theme ${RASI}
