[ui]
ui_scale = 100
orientation = "portrait"
theme = "catppuccin-mocha-mauve.toml"
[ui.input_bar]
position = "bottom"
prompt = "❯"
border_type = "none" # https://docs.rs/ratatui/latest/ratatui/widgets/block/enum.BorderType.html#variants
[ui.status_bar]
hidden = true
[ui.results_panel]
border_type = "none"
[ui.preview_panel]
size = 50
#header = ""
#footer = ""
scrollbar = false
border_type = "none"
# padding = {"left": 0, "right": 0, "top": 0, "bottom": 0}
hidden = true

[ui.help_panel]
# Whether to split the help panel by categories
show_categories = false
hidden = true

[ui.remote_control]
# Whether to show channel descriptions in remote control mode
show_channel_descriptions = false
# Whether to sort channels alphabetically
sort_alphabetically = true
disabled = true
