# https://wiki.hypr.land/hypr-ecosystem/user/hyprtoolkit/
background = 0xFF11111B
base = 0xFF1E1E2E
text = 0xFFCDD6F4
alternate_base = 0xFF181825
bright_text = 0xFFF5E0DC
accent = 0xFF94E2D5
accent_secondary = 0xFF94E2D5
font_size = 14
