{inputs, ...}: {
  imports = [inputs.den.flakeModule];

  den.aspects.bar = {
    treefmt.programs.nixfmt.enable = true;

    tests.test-math-works = {
      expr = 22 * 2;
      expected = 44;
    };

    packages = {config, ...}: {
      write-files = config.files.writer.drv;
    };

    files = {pkgs, ...}: {
      file."README.md".text = ''
        # Example Den custom classes for flake-parts modules and perSystem outputs.

        This example showcases Den forward classes for third-party flake-parts modules.

        This README is generated by `nix run .#write-files`.

        See den.nix and flake-parts.nix
      '';
    };

    devshell = {
      pkgs,
      self',
      ...
    }: {
      commands = [
        {
          package = self'.packages.write-files;
        }
      ];
      packages = [
        pkgs.hello
      ];
    };
  };
}
