# https://wiki.hypr.land/hypr-ecosystem/user/hyprpaper/

splash = false

wallpaper {
  monitor = DP-3
  path = ~/.dotfiles/config/wallpapers
  recursive = true
}


wallpaper {
  monitor = DP-2
  path = ~/.dotfiles/config/wallpapers
  recursive = true
}
