# https://wiki.hypr.land/hypr-ecosystem/user/hyprtoolkit/
# https://github.com/catppuccin/hyprtoolkit/blob/main/themes/mocha/catppuccin-mocha-mauve.conf
background = 0xFF11111B
base = 0xFF1E1E2E
text = 0xFFCDD6F4
alternate_base = 0xFF181825
bright_text = 0xFFF5E0DC
accent = 0xFFCBA6F7
accent_secondary = 0xFFCBA6F7
h1_size = 14
h2_size = 12
font_size = 12
rounding_large = 2
rounding_small = 1
