#:schema https://mise.jdx.dev/schema/mise.json

# References
# [cli](https://mise.jdx.dev/cli/)
# [toml](https://toml.io/en/v1.1.0)
# [tera](https://mise.jdx.dev/templates.html#template-rendering)
# [configuration](https://mise.jdx.dev/configuration.html#configuration)

# [Tools](https://mise.jdx.dev/dev-tools/#dev-tools)
# [Versions](https://mise-versions.jdx.dev/)
# [github backend](https://mise.jdx.dev/dev-tools/backends/github.html)
# [http](https://mise.jdx.dev/dev-tools/backends/http.html)

[tool_alias]
oxlint = "github:oxc-project/oxc"
oxfmt = "github:oxc-project/oxc"
vite-plus = "github:voidzero-dev/vite-plus"
sesh = "github:joshmedeski/sesh"


[tools]
# Runtimes and Compilers

rust = "latest"

# OTP
elixir = "latest"
erlang = "latest"

# Javascript
node = "latest"
bun = "latest"

# JVM
java = "openjdk-17"
kotlin = "2.1.0"

# Package Managers
pnpm = "latest"
uv = "latest"
aube = "latest"

# LSP
expert = "latest"
"npm:oxlint-tsgolint" = "latest"


# Utils
usage = "latest"
jq = "latest"
pitchfork = "latest"
watchexec = "latest"


# Build tools
bazel = "latest"


[tools.oxlint]
version = "apps_v1.79.0"
matching = "oxlint"
rename_exe = "oxlint"

[tools.oxfmt]
version = "apps_v1.79.0"
matching = "oxfmt"
rename_exe = "oxfmt"

[tools.vite-plus]
version = "v0.2.9"
matching = "vp"
rename_exe = "vp"

[tools.sesh]
version = "v2.28.0"

[tools."http:winbox"]
version = "4.3"
url = "https://download.mikrotik.com/routeros/winbox/{{ version }}/WinBox_Linux.zip"
checksum_url = "https://download.mikrotik.com/routeros/winbox/{{ version }}/WinBox_Linux.zip.sha256"


# # Terminal Goodies
# herdr = "latest"
#
# # Build tools
# bazel = "latest"
#
# # Harness
# opencode = "latest"
# "npm:context-mode" = "latest"
# "npm:@earendil-works/pi-coding-agent" = "latest"
# "cargo:zeroclawlabs" = "latest"
# copilot = "latest"
# portless = "latest"
# agy = "latest"


# [Tools Deps](https://mise.jdx.dev/dev-tools/deps.html#deps)
[deps]


[hooks] # [Hooks](https://mise.jdx.dev/hooks.html#hooks)
