#!/bin/bash

if pgrep -x "rofi" >/dev/null; then
  # Rofi is running, kill it
  pkill -x rofi
  exit 0
fi

# Get focused output from swaymsg
focused_output=$(swaymsg -t get_outputs | jq -r '.[] | select(.focused == true) | .name')

# Forward all arguments to rofi with focused monitor
exec rofi -m "$focused_output" "$@"
