#!/usr/bin/env bash

# Get Colors
DIR="$HOME/.config/sway"
background="$(cat $HOME/.config/rofi/mini.rasi | grep 'background:' | cut -d':' -f2 | tr -d ' '\;)"
accent="$(cat $HOME/.config/rofi/mini.rasi | grep 'selected:' | cut -d':' -f2 | tr -d ' '\;)"

# Import Current Theme
RASI="$HOME/.config/rofi/screenshot.rasi"

# Theme Elements
prompt='Screenshot'
mesg="Directory :: $(xdg-user-dir PICTURES)/Screenshots"

# Options
layout=$(cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2)
if [[ "$layout" == 'NO' ]]; then
  option_1="󰡊 Capture Area"
  option_2=" Capture Desktop"
  option_3="󰞣 Capture Window"
  option_4="󰻜 Capture in 5s"
else
  option_1="󰡊"
  option_2=""
  option_3="󰞣"
  option_4="󰻜"

fi

rofi_focused="$HOME/.config/sway/scripts/rofi_focused"

# Rofi CMD
rofi_cmd() {
  "$rofi_focused" -dmenu \
    -p "$prompt" \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${RASI}
}

# Pass variables to rofi dmenu
run_rofi() {
  echo -e "$option_1\n$option_2\n$option_3\n$option_4" | rofi_cmd
}

# Screenshot
time=$(date +%Y-%m-%d-%H-%M-%S)
dir="$(xdg-user-dir PICTURES)/Screenshots"
file="Screenshot_${time}.png"

# New Screenshot Script Path
SCREENSHOT_SCRIPT="$HOME/.config/sway/scripts/screenshot"

# Execute Command
run_cmd() {
  if [[ "$1" == '--opt1' ]]; then
    "$SCREENSHOT_SCRIPT" --area
  elif [[ "$1" == '--opt2' ]]; then
    "$SCREENSHOT_SCRIPT" --now
  elif [[ "$1" == '--opt3' ]]; then
    "$SCREENSHOT_SCRIPT" --win
  elif [[ "$1" == '--opt4' ]]; then
    "$SCREENSHOT_SCRIPT" --in5
  fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
$option_1)
  run_cmd --opt1
  ;;
$option_2)
  run_cmd --opt2
  ;;
$option_3)
  run_cmd --opt3
  ;;
$option_4)
  run_cmd --opt4
  ;;
esac
