return {
  -- {
  --   'neovim/nvim-lspconfig',
  --   opts = {
  --     servers = {
  --       -- https://github.com/oxalica/nil/blob/main/docs/configuration.md
  --       -- nil_ls = {
  --       --   formatting = {
  --       --     command = { 'nixfmt' },
  --       --   },
  --       --   flake = {
  --       --     autoArchive = false,
  --       --     autoEvalInputs = true,
  --       --   },
  --       -- },
  --       -- https://github.com/nix-community/nixd/blob/main/nixd/docs/configuration.md
  --       nixd = {
  --         nixpkgs = {
  --           expr = 'import <nixpkgs> { }',
  --           -- expr = '(builtins.getFlake "/PATH/TO/FLAKE").nixosConfigurations.CONFIGNAME.options',
  --         },
  --         formatting = {
  --           command = { 'nixfmt', 'alejandra' }, -- or nixfmt or nixpkgs-fmt
  --         },
  --         -- options = {
  --         --   nixos = {
  --         --       expr = '(builtins.getFlake "/PATH/TO/FLAKE").nixosConfigurations.CONFIGNAME.options',
  --         --   },
  --         --   home_manager = {
  --         --       expr = '(builtins.getFlake "/PATH/TO/FLAKE").homeConfigurations.CONFIGNAME.options',
  --         --   },
  --         -- },        },
  --       },
  --     },
  --   },
  -- },
}
