-- opts = function(_, opts)
--   local lint = require("lint")
--   local util = require("lint.util")
--   local parser = require("lint.parser")
--   local oxlint = require("lint.linters.oxlint")
--   local ns = lint.get_namespace("oxlint")
--   opts.sources = cmp.config.sources(vim.list_extend(opts.sources, { { name = "emoji" } }))
-- end,

local pattern = "::([^ ]+) file=(.*),line=(%d+),endLine=(%d+),col=(%d+),endColumn=(%d+),title=(.*)::(.*)"
local severities = {
  ["error"] = vim.diagnostic.severity.ERROR,
  ["warning"] = vim.diagnostic.severity.WARN,
}
local groups = { "severity", "file", "lnum", "end_lnum", "col", "end_col", "code", "message" }
local defaults = { ["source"] = "oxlint" }
local binary_name = "vp"

return {

  {
    "mfussenegger/nvim-lint",
    opts = {
      linters = {
        ["markdownlint-cli2"] = {
          args = { "--disable", "MD013", "--" },
        },
      },
      -- linters_by_ft = {
      --   javascript = { "oxlint", "biomejs", stop_after_first = true },
      --   javascriptreact = { "oxlint", "biomejs", stop_after_first = true },
      --   typescript = { "oxlint", "biomejs", stop_after_first = true },
      --   typescriptreact = { "oxlint", "biomejs", stop_after_first = true },
      --   json = { "oxlint", "biomejs", stop_after_first = true },
      --   vue = { "oxlint", "biomejs", stop_after_first = true },
      --   svelte = { "oxlint", "biomejs", stop_after_first = true },
      --   astro = { "oxlint", "biomejs", stop_after_first = true },
      -- },
    },

    --   {
    --     "mfussenegger/nvim-lint",
    --     events = { "BufWritePost", "BufReadPost", "InsertLeave" },
    --     opts = function(_, opts)
    --       opts.linters.oxlint = {
    --         cmd = function()
    --           local local_binary = vim.fn.fnamemodify(vim.fn.getcwd() .. "/node_modules/.bin/vp", ":p")
    --           -- Use vim.uv for Neovim 0.10+, fallback to vim.loop for older versions
    --           return (vim.uv or vim.loop).fs_stat(local_binary) and local_binary or "vp"
    --         end,
    --         stdin = false,
    --         args = {
    --           "lint",
    --           function()
    --             return vim.api.nvim_buf_get_name(0)
    --           end,
    --           "--",
    --           "--format",
    --           "json",
    --         }, -- Switched to JSON format
    --         stream = "stdout",
    --         ignore_exitcode = true,
    --         parser = function(output, bufnr)
    --           if output == "" then
    --             return {}
    --           end
    --
    --           -- Extract the JSON array cleanly (ignores any trailing terminal text)
    --           local json_str = output:match("%[.*%]") or output
    --           local success, decoded = pcall(vim.json.decode, json_str)
    --
    --           if not success or not decoded then
    --             return {}
    --           end
    --
    --           -- Handle edge cases depending on if oxlint wraps the array in an object
    --           local items = {}
    --           if type(decoded) == "table" then
    --             items = decoded[1] and decoded or (decoded.diagnostics or {})
    --           end
    --
    --           local diagnostics = {}
    --           for _, item in ipairs(items) do
    --             local lnum = 0
    --             local col = 0
    --             local end_lnum = 0
    --             local end_col = 0
    --
    --             -- Start with the base message
    --             local full_message = item.message
    --
    --             -- Oxc labels provide 1-indexed lines/columns, Neovim API needs 0-indexed
    --             if item.labels and #item.labels > 0 then
    --               local span = item.labels[1].span
    --               lnum = math.max(0, (span.line or 1) - 1)
    --               col = math.max(0, (span.column or 1) - 1)
    --               end_lnum = lnum
    --               end_col = col + (span.length or 0)
    --
    --               -- Append label details to create a multi-line message
    --               for _, label_obj in ipairs(item.labels) do
    --                 if label_obj.label then
    --                   -- The \n forces Trouble and the floating window to render a new line
    --                   full_message = full_message .. "\n  └─ " .. label_obj.label
    --                 end
    --               end
    --             end
    --
    --             local severity = vim.diagnostic.severity.ERROR
    --             if item.severity == "warning" then
    --               severity = vim.diagnostic.severity.WARN
    --             end
    --
    --             table.insert(diagnostics, {
    --               lnum = lnum,
    --               col = col,
    --               end_lnum = end_lnum,
    --               end_col = end_col,
    --               severity = severity,
    --               source = "oxlint",
    --               message = full_message, -- Use the newly constructed string
    --               code = item.code,
    --               reference = {
    --                 url = item.url,
    --                 related = item.related or {},
    --               },
    --             })
    --           end
    --
    --           return diagnostics
    --         end,
    --       }
    --
    --       -- Safely append to existing linters_by_ft
    --       opts.linters_by_ft = opts.linters_by_ft or {}
    --       local filetypes = { "javascript", "javascriptreact", "typescript", "typescriptreact", "vue", "svelte", "astro" }
    --
    --       for _, ft in ipairs(filetypes) do
    --         opts.linters_by_ft[ft] = { "oxlint" }
    --       end
    --     end,
    --   },
    -- },
    -- {
    --   "mfussenegger/nvim-lint",
    --   event = "LazyFile",
    --   opts = {
    --     -- Event to trigger linters
    --     events = { "BufWritePost", "BufReadPost", "InsertLeave" },
    --     linters_by_ft = {
    --       -- fish = { "fish" },
    --       -- Use the "*" filetype to run linters on all filetypes.
    --       -- ['*'] = { 'global linter' },
    --       -- Use the "_" filetype to run linters on filetypes that don't have other linters configured.
    --       -- ['_'] = { 'fallback linter' },
    --       -- ["*"] = { "typos" },
    --     },
    --     -- LazyVim extension to easily override linter options
    --     -- or add custom linters.
    --     ---@type table<string,table>
    --     linters = {
    --       ["markdownlint-cli2"] = {
    --         args = { "--disable", "MD013", "--" },
    --       },
    --
    --       -- -- Example of using selene only when a selene.toml file is present
    --       -- selene = {
    --       --   -- `condition` is another LazyVim extension that allows you to
    --       --   -- dynamically enable/disable linters based on the context.
    --       --   condition = function(ctx)
    --       --     return vim.fs.find({ "selene.toml" }, { path = ctx.filename, upward = true })[1]
    --       --   end,
    --       -- },
    --     },
    --   },
    --   config = function(_, opts)
    --     local M = {}
    --
    --     local lint = require("lint")
    --     for name, linter in pairs(opts.linters) do
    --       if type(linter) == "table" and type(lint.linters[name]) == "table" then
    --         lint.linters[name] = vim.tbl_deep_extend("force", lint.linters[name], linter)
    --         if type(linter.prepend_args) == "table" then
    --           lint.linters[name].args = lint.linters[name].args or {}
    --           vim.list_extend(lint.linters[name].args, linter.prepend_args)
    --         end
    --       else
    --         lint.linters[name] = linter
    --       end
    --     end
    --     lint.linters_by_ft = opts.linters_by_ft
    --
    --     function M.debounce(ms, fn)
    --       local timer = vim.uv.new_timer()
    --       return function(...)
    --         local argv = { ... }
    --         timer:start(ms, 0, function()
    --           timer:stop()
    --           vim.schedule_wrap(fn)(unpack(argv))
    --         end)
    --       end
    --     end
    --
    --     function M.lint()
    --       -- Use nvim-lint's logic first:
    --       -- * checks if linters exist for the full filetype first
    --       -- * otherwise will split filetype by "." and add all those linters
    --       -- * this differs from conform.nvim which only uses the first filetype that has a formatter
    --       local names = lint._resolve_linter_by_ft(vim.bo.filetype)
    --
    --       -- Create a copy of the names table to avoid modifying the original.
    --       names = vim.list_extend({}, names)
    --
    --       -- Add fallback linters.
    --       if #names == 0 then
    --         vim.list_extend(names, lint.linters_by_ft["_"] or {})
    --       end
    --
    --       -- Add global linters.
    --       vim.list_extend(names, lint.linters_by_ft["*"] or {})
    --
    --       -- Filter out linters that don't exist or don't match the condition.
    --       local ctx = { filename = vim.api.nvim_buf_get_name(0) }
    --       ctx.dirname = vim.fn.fnamemodify(ctx.filename, ":h")
    --       names = vim.tbl_filter(function(name)
    --         local linter = lint.linters[name]
    --         if not linter then
    --           LazyVim.warn("Linter not found: " .. name, { title = "nvim-lint" })
    --         end
    --         return linter and not (type(linter) == "table" and linter.condition and not linter.condition(ctx))
    --       end, names)
    --
    --       -- Run linters.
    --       if #names > 0 then
    --         lint.try_lint(names)
    --       end
    --     end
    --
    --     vim.api.nvim_create_autocmd(opts.events, {
    --       group = vim.api.nvim_create_augroup("nvim-lint", { clear = true }),
    --       callback = M.debounce(100, M.lint),
    --     })
    --   end,
    -- },
  },
}
