#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/i3"
STYLE="artifex"
RASI="$DIR/themes/$STYLE/rofi/windows.rasi"

# Run
rofi \
    -show window \
	-theme ${RASI}
