return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      if type(opts.ensure_installed) == "table" then
        vim.list_extend(opts.ensure_installed, {
          "astro",
          "css",
          "cpp",
          "caddy",
          "html",
          "gleam",
          "graphql",
          "javascript",
          "json",
          "lua",
          -- "mdx",
          "markdown",
          -- "markdown_inline",
          "prisma",
          "svelte",
          "java",
          "kotlin",
          "slint",
          "tsx",
          "typescript",
          "vue",
          -- "astro",
          -- "bash",
          -- "css",
          -- "csv",
          -- "desktop",
          -- "diff",
          -- "dockerfile",
          -- "cpp",
          -- "html",
          -- "gleam",
          -- "elixir",
          -- "eex",
          -- "gitignore",
          -- "gitcommit",
          -- "ssh_config",
          -- "terraform",
          -- "jsdoc",
          -- "heex",
          -- "graphql",
          -- "javascript",
          -- "nix",
          -- "json",
          -- "lua",
          -- -- "markdown",
          -- -- "markdown_inline",
          -- "svelte",
          -- "java",
          -- "kotlin",
          -- "slint",
          -- "tsx",
          -- "typescript",
          -- "xml",
          -- "vue",
          -- "zsh",
        })
      end
      -- table.insert(opts.incremental_selection, { enable = false })
      -- table.insert(opts.autotag, { enable = true })
    end,
  },
  {
    "davidmh/mdx.nvim",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
}
