[symlinks]
"helix\\config.toml" = "C:\\Users\\Administrator/.config/helix\\config.toml"
"helix\\themes\\artifex.toml" = "C:\\Users\\Administrator/.config/helix\\themes\\artifex.toml"
"nvim\\.gitignore" = "C:\\Users\\Administrator/AppData/Local/nvim\\.gitignore"
"nvim\\.neoconf.json" = "C:\\Users\\Administrator/AppData/Local/nvim\\.neoconf.json"
"nvim\\LICENSE" = "C:\\Users\\Administrator/AppData/Local/nvim\\LICENSE"
"nvim\\README.md" = "C:\\Users\\Administrator/AppData/Local/nvim\\README.md"
"nvim\\init.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\init.lua"
"nvim\\lazy-lock.json" = "C:\\Users\\Administrator/AppData/Local/nvim\\lazy-lock.json"
"nvim\\lua\\config\\autocmds.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\config\\autocmds.lua"
"nvim\\lua\\config\\keymaps.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\config\\keymaps.lua"
"nvim\\lua\\config\\lazy.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\config\\lazy.lua"
"nvim\\lua\\config\\options.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\config\\options.lua"
"nvim\\lua\\config\\utils.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\config\\utils.lua"
"nvim\\lua\\plugins\\alpha.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\alpha.lua"
"nvim\\lua\\plugins\\clipboard.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\clipboard.lua"
"nvim\\lua\\plugins\\cmp.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\cmp.lua"
"nvim\\lua\\plugins\\colorscheme.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\colorscheme.lua"
"nvim\\lua\\plugins\\example.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\example.lua"
"nvim\\lua\\plugins\\neo-tree.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\neo-tree.lua"
"nvim\\lua\\plugins\\notify.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\notify.lua"
"nvim\\lua\\plugins\\tailwind.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\tailwind.lua"
"nvim\\lua\\plugins\\telescope.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\telescope.lua"
"nvim\\lua\\plugins\\typescript.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\typescript.lua"
"nvim\\lua\\plugins\\util.lua" = "C:\\Users\\Administrator/AppData/Local/nvim\\lua\\plugins\\util.lua"
"nvim\\stylua.toml" = "C:\\Users\\Administrator/AppData/Local/nvim\\stylua.toml"
pwsh = "C:\\Users\\Administrator/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
starship = "C:\\Users\\Administrator/.config/starship.toml"
wezterm = "C:\\Users\\Administrator/.wezterm.lua"

[templates]
