[symlinks]
"helix/config.toml" = "/home/artifex/.config/helix/config.toml"
"helix/themes/artifex.toml" = "/home/artifex/.config/helix/themes/artifex.toml"
"nvim/.gitignore" = "/home/artifex/.config/nvim/.gitignore"
"nvim/.neoconf.json" = "/home/artifex/.config/nvim/.neoconf.json"
"nvim/LICENSE" = "/home/artifex/.config/nvim/LICENSE"
"nvim/README.md" = "/home/artifex/.config/nvim/README.md"
"nvim/init.lua" = "/home/artifex/.config/nvim/init.lua"
"nvim/lazy-lock.json" = "/home/artifex/.config/nvim/lazy-lock.json"
"nvim/lua/config/autocmds.lua" = "/home/artifex/.config/nvim/lua/config/autocmds.lua"
"nvim/lua/config/keymaps.lua" = "/home/artifex/.config/nvim/lua/config/keymaps.lua"
"nvim/lua/config/lazy.lua" = "/home/artifex/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/options.lua" = "/home/artifex/.config/nvim/lua/config/options.lua"
"nvim/lua/config/utils.lua" = "/home/artifex/.config/nvim/lua/config/utils.lua"
"nvim/lua/plugins/alpha.lua" = "/home/artifex/.config/nvim/lua/plugins/alpha.lua"
"nvim/lua/plugins/clipboard.lua" = "/home/artifex/.config/nvim/lua/plugins/clipboard.lua"
"nvim/lua/plugins/cmp.lua" = "/home/artifex/.config/nvim/lua/plugins/cmp.lua"
"nvim/lua/plugins/colorscheme.lua" = "/home/artifex/.config/nvim/lua/plugins/colorscheme.lua"
"nvim/lua/plugins/example.lua" = "/home/artifex/.config/nvim/lua/plugins/example.lua"
"nvim/lua/plugins/neo-tree.lua" = "/home/artifex/.config/nvim/lua/plugins/neo-tree.lua"
"nvim/lua/plugins/notify.lua" = "/home/artifex/.config/nvim/lua/plugins/notify.lua"
"nvim/lua/plugins/tailwind.lua" = "/home/artifex/.config/nvim/lua/plugins/tailwind.lua"
"nvim/lua/plugins/telescope.lua" = "/home/artifex/.config/nvim/lua/plugins/telescope.lua"
"nvim/lua/plugins/typescript.lua" = "/home/artifex/.config/nvim/lua/plugins/typescript.lua"
"nvim/lua/plugins/util.lua" = "/home/artifex/.config/nvim/lua/plugins/util.lua"
"nvim/stylua.toml" = "/home/artifex/.config/nvim/stylua.toml"
starship = "/home/artifex/.config/starship.toml"
tmux = "/home/artifex/.tmux.config"
wezterm = "/home/artifex/.wezterm.lua"
zshrc = "/home/artifex/.zshrc"

[templates]
