[helpers]

[vim.files]
nvim = "~/.config/nvim"

[helix.files]
helix = "~/.config/helix"

[shell.files]
lazygit = "~/.config/lazygit/config.yml"
zshrc = "~/.zshrc"
starship = "~/.config/starship.toml"
tmux = "~/.tmux.config"
wezterm = "~/.wezterm.lua"

