[helpers]

[vim.files]
nvim = "~/.config/nvim"
nvimone = "~/.config/nvimone"

[helix.files]
helix = "~/.config/helix"

[shell.files]
bashrc = "~/.bashrc"
alacritty = "~/.alacritty.yaml"
lazygit = "~/.config/lazygit/config.yml"
zshrc = "~/.zshrc"
starship = "~/.config/starship.toml"
tmux = "~/.tmux.conf"
wezterm = "~/.wezterm.lua"
