[helpers]

[wezterm.files]
wezterm = "~/.config/wezterm"

[vim.files]
nvim = "~/.config/nvim"
vscodenvim = "~/.config/nvimartifex"

[helix.files]
helix = "~/.config/helix"

[shell.files]
bashrc = "~/.bashrc"
lazygit = "~/.config/lazygit/config.yml"
gitui = "~/.config/gitui"
zshrc = "~/.zshrc"
starship = "~/.config/starship.toml"
tmux = "~/.tmux.conf"
tmuxifier = "~/.tmux/layouts"

[terminal.files]
alacritty = "~/.config/alacritty"
btop = "~/.config/btop"

[archcraft.files]
# "archcraft/i3" = "~/.config/i3"
# "archcraft/bspwm" = "~/.config/bspwm"
