[vim.files]
nvim = "~/AppData/Local/nvim"
pwsh = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
# [files]
# pwsh = "~/Documents/Powershell/Microsoft.Powershell_profile.ps1"


# [shell.files]
# pwsh = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
