[vim.files]
nvim = "~/AppData/Local/nvimartifex"
vscodenvim = "~/AppData/Local/nvim"

[helix.files]
helix = "~/Appdata/Roaming/helix"

[shell.files]
bashrc = ""
zshrc = ""
alacritty = "~/Appdata/Roaming/alacritty/alacritty.yml"
pwsh = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
lazygit = "~/AppData/Roaming/lazygit/config.yml"
starship = "~/.config/starship.toml"
bashrcw = "~/.bashrc"
