# Layout Configuration for Mango WM

default_mode = dwindle

# Scroller Layout Setting
scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=0
scroller_prefer_center=0
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout Setting
new_is_master=0
default_mfact=0.5
default_nmaster=1
tag_num=9
smartgaps=0
center_master_overspread=0
center_when_single_stack=0

# Dwindle Layout Setting
dwindle_smart_split=0
dwindle_drop_simple_split=1
dwindle_manual_split=0
dwindle_hsplit=1
dwindle_vsplit=1
dwindle_preserve_split=0

# Overview Setting
hotarea_size=10
enable_hotarea=0
hotarea_disable_on_fullscreen=1
overviewgappi=5
overviewgappo=30
overcircle_center_ratio=0.5

# Tag Layout Rules
# Supported layouts: tile, scroller, grid, deck, monocle, center_tile, vertical_tile, vertical_scroller
# tagrule=id:1,layout_name:dwindle
# tagrule=id:2,layout_name:dwindle
# tagrule=id:3,layout_name:dwindle
# tagrule=id:4,layout_name:dwindle
# tagrule=id:5,layout_name:dwindle
# tagrule=id:6,layout_name:dwindle
# tagrule=id:7,layout_name:dwindle
# tagrule=id:8,layout_name:dwindle
# tagrule=id:9,layout_name:dwindle

# =====================================================================
# Monitor 1 (DP-1) - Tags 1 to 5
# =====================================================================
tagrule=id:1,monitor:DP-2,layout_name:dwindle
tagrule=id:2,monitor:DP-2,layout_name:dwindle
tagrule=id:3,monitor:DP-2,layout_name:dwindle
tagrule=id:4,monitor:DP-2,layout_name:dwindle
tagrule=id:5,monitor:DP-2,layout_name:vertical_scroller

# =====================================================================
# Monitor 2 (DP-2) - Tags 6 to 10
# =====================================================================
tagrule=id:6,monitor:DP-3,layout_name:scroller
tagrule=id:7,monitor:DP-3,layout_name:dwindle
tagrule=id:8,monitor:DP-3,layout_name:grid
tagrule=id:9,monitor:DP-3,layout_name:dwindle
tagrule=id:10,monitor:DP-3,layout_name:dwindle
