# Miscellaneous Window Manager Behavior for Mango WM

no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
idleinhibit_when_fullscreen=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=1
focusdir_only_zone_overlap=0
exchange_cross_monitor=1
auto_reload_config=1
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
float_full_to_top=0
cursor_size=24
drag_tile_to_tile=1
drag_tile_small=1
