[general]
live_config_reload = true
ipc_socket = true
import = [
  # "~/.config/alacritty/tokyo-night-storm.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/keys.toml",
]

[colors]
draw_bold_text_with_bright_colors = true


[env]
TERM = "alacritty"
# TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = false
opacity = 0.82
blur = false
startup_mode = "Windowed"
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

## Number of lines/columns (not pixels) in the terminal.
[window.dimensions]
columns = 150
lines = 73


[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


# [debug]
# renderer = "glsl3"


# [[hints.enabled]]
# command = "xdg-open"
# hyperlinks = true
# post_processing = true
# persist = false
# mouse.enabled = true
# binding = { key = "U", mods = "Control|Shift" }
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"


# [shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux new"]
