import = [
  # "~/.config/alacritty/tokyo-night-storm.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/keys.toml",
]
live_config_reload = true
# renderer = "glsl3"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
opacity = 0.93
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0

[scrolling]
history = 50000
multiplier = 3


[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux new"]
