-- vim.pack.add({ 'https://github.com/lewis6991/hover.nvim' })
--
-- require('hover').config({
--   init = function()
--     -- Require providers
--     require('hover.providers.diagnostic')
--     require('hover.providers.lsp')
--     require('hover.providers.dap')
--     require('hover.providers.man')
--     require('hover.providers.gh')
--     require('hover.providers.gh_user')
--     -- require('hover.providers.jira')
--     -- require('hover.providers.fold_preview')
--     require('hover.providers.dictionary')
--   end,
--   preview_opts = {
--     border = 'single',
--   },
--   -- Whether the contents of a currently open hover window should be moved
--   -- to a :h preview-window when pressing the hover keymap.
--   preview_window = false,
--   title = true,
--   mouse_providers = {
--     'hover.providers.lsp',
--   },
--   mouse_delay = 1000,
-- })
--
-- -- Setup keymaps
-- vim.keymap.set('n', 'K', function() require('hover').open() end, { desc = 'hover.nvim (open)' })
--
-- vim.keymap.set('n', 'gK', function() require('hover').enter() end, { desc = 'hover.nvim (enter)' })
--
-- vim.keymap.set(
--   'n',
--   '<C-p>',
--   function() require('hover').switch('previous') end,
--   { desc = 'hover.nvim (previous source)' }
-- )
--
-- vim.keymap.set('n', '<C-n>', function() require('hover').switch('next') end, { desc = 'hover.nvim (next source)' })
--
-- -- Mouse support
-- vim.keymap.set('n', '<MouseMove>', function() require('hover').mouse() end, { desc = 'hover.nvim (mouse)' })
--
-- vim.o.mousemoveevent = true
