-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		border_size = 1,
		resize_on_border = false,
	},
	decoration = {
		rounding = 0,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:.*$" },
	xray = true,
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
