-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:LG Electronics LG ULTRAGEAR 308NTGY1D007", mode = "2560x1440@164.958", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "desc:GIGA-BYTE TECHNOLOGY CO. LTD. AORUS AD27QD 19110B001090", mode = "2560x1440@143.972", position = "2560x0", scale = 1, vrr = 2 })
