# More options: https://github.com/DreamMaoMao/mango/wiki/
# Mango Window Manager Main Configuration

# --- Core Modules ---
# moved to nix config
# source = ./config.d/autostart.conf
source = ./config.d/appearance.conf
source = ./config.d/theme.conf
source = ./config.d/animations.conf
source = ./config.d/layouts.conf
source = ./config.d/input.conf
source = ./config.d/misc.conf
source = ./config.d/bindings.conf
source = ./config.d/rules.conf

# --- Local Machine Overrides (Optional) ---
source-optional = ./local.conf
