#:schema https://mise.jdx.dev/schema/mise.json

# General Settings
[settings]
experimental = true
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

# Bootstrap
[bootstrap.user]
login_shell = "/bin/zsh"

[bootstrap.repos]
"~/.dotfiles" = { url = "https://github.com/directormac/dotfiles.git", ref = "mised" }

[bootstrap.packages]
"pacman:openssh" = "latest" # install for remote machines

# Essentials
"pacman:base" ="latest"
"pacman:base-devel" ="latest"
"pacman:git" = "latest"
"pacman:7zip" = "latest"
"pacman:curl" = "latest"
"pacman:wget" = "latest"
"pacman:man" = "latest"
"pacman:lshw" = "latest"
"pacman:github-cli" = "latest"
"pacman:vim" = "latest"
"pacman:inotify-tools" = "latest"
"pacman:neovim" = "latest"

# Terminal Essentials
"pacman:bat" = "latest"
"pacman:btop" = "latest"
"pacman:dust" = "latest"
"pacman:fd" = "latest"
"pacman:fzf" = "latest"
"pacman:jq" = "latest"
"pacman:lazydocker" = "latest"
"pacman:lazygit" = "latest"
"pacman:less" = "latest"
"pacman:lsd" = "latest"
"pacman:navi" = "latest"
"pacman:ripgrep" = "latest"
"pacman:tmux" = "latest"
"pacman:ueberzugpp" = "latest"
"pacman:starship" = "latest"
"pacman:tealdeer" = "latest"
"pacman:websocat" = "latest"
"pacman:yazi" = "latest"
"pacman:yq" = "latest"
"pacman:zoxide" = "latest"

# Extra
"pacman:ffmpeg" = "latest"
"pacman:poppler" = "latest"
"pacman:resvg" = "latest"

[bootstrap.mise_shell_activate]
zprofile = {enabled = true, mode = "shims"}
zshrc = {enabled = true, mode = "activate"}

[dotfiles]
"~/.zshrc" = {}
"~/.bashrc" = {}
"~/.gitconfig" = {}
"~/.config/mise/config.toml" = "~/.dotfiles/config/mise/config.toml"



# Tools
[tools]
rust = "latest"



# Shell Aliases
[shell_alias]
lzg = "lazygit"
lzd = "lazydocker"
ll = "ls -la"
la = "ls -A"
gs = "git status"
gc = "git commit"


