#:schema https://mise.jdx.dev/schema/mise.json

[tools]
elixir = "1.19.5-otp-28"
erlang = "28.4.1"
"aqua:elixir-lang/expert" = "0.1.0"
java = "openjdk-17"
jq = "1.7"
kotlin = "2.1.0"
node = "latest"
bun = "latest"
pnpm = "latest"
pitchfork = "2.0.0"
opencode = "1.3.15"
gemini-cli = "0.36.0"
"npm:context-mode" = "1.0.74"

[settings]
trusted_config_paths = ['~/.dotfiles', '~/Code']
# env_file = '.env.development'
experimental = true
not_found_auto_install = true
task_output = "prefix"
npm = { package_manager = "bun" }

[shell_alias]
phxdev = "iex --name phxdev@127.0.0.1 --cookie secret -S mix phx.server"
