#:schema https://mise.jdx.dev/schema/mise.json

# References
# [cli](https://mise.jdx.dev/cli/)
# [toml](https://toml.io/en/v1.1.0)
# [tera](https://mise.jdx.dev/templates.html#template-rendering)
# [configuration](https://mise.jdx.dev/configuration.html#configuration)

[env]
# VP_PR_VERSION = ""

[tools]
# Runtimes
elixir = "1.20.2-otp-28"
erlang = "28.5"

node = "latest"
bun = "latest"

java = "openjdk-17"
kotlin = "2.1.0"

# Package Managers
pnpm = "latest"
uv = "latest"
aube = "latest"

# LSP
expert = "0.1.8"

# Utils
jq = "1.7"
pitchfork = "latest"
watchexec = "latest"

# Terminal Goodies
herdr = "latest"

# Build tools
bazel = "latest"

# Harness
opencode = "latest"
"npm:context-mode" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"cargo:zeroclawlabs" = "latest"
copilot = "latest"
portless = "latest"
agy = "latest"

[settings]
trusted_config_paths = ['~/.dotfiles', '~/Code']
experimental = true
not_found_auto_install = true
task.output = "prefix"
idiomatic_version_file_enable_tools = []
npm = { package_manager = "bun" }
minimum_release_age_excludes = ["bun", "expert"]

